### ISSUE TITLE
DISP connected to VDD?

### ISSUE THREAD

**Issue by Percentnineteen** [karnadii/sharp_memory_display_breakout#1]
Hi, I was reviewing the documentation and was wondering why the connection up to VDD was omitted for the DISP pin? Was this an oversight?

**Comment by karnadii** [comment]
are you reading the correct datasheet? DISP pin should not be connected to VDD at all

**Comment by karnadii** [comment]
make sure you have the correct datahseet https://www.sharpsde.com/products/displays/model/ls011b7dh03/

**Comment by Percentnineteen** [comment]
The datasheet says DISP is the on/off control for the display and has this note:
The display ON/OFF signal is only for display.
Data in the memory will be saved at the time of ON/OFF.
When it’s “Hi”, data in the memory will display, when it’s “Lo”, white color will display and
data in the memory will be saved.

The Adafruit implementation has the signal tied to a generated 3.3v (not VDD) through a 10k resistor (so the display is permanently on).

I guess what I'm asking is that I don't see any path to "Hi" in the schematic. It's possible I'm still reading something wrong, though.

**Comment by karnadii** [comment]
I think either way will work. since I have tested the schematic. but I have updated the file with 10k pull up resistor to address your concern.

**Comment by karnadii** [comment]
@Percentnineteen you are right, the connection between VDD and DISP is important. I have ordered and soldered my last revision with the 10k pull up resistor. It works, when removing the pull up resistor it is not working. it is weird the first design work without problem. Thanks for pointing it out and make an issue.

**Comment by Percentnineteen** [comment]
The datasheet says DISP is the on/off control for the display and has this
note:
The display ON/OFF signal is only for display.
Data in the memory will be saved at the time of ON/OFF.
When it’s “Hi”, data in the memory will display, when it’s “Lo”, white
color will display and
data in the memory will be saved.

The Adafruit implementation has the signal tied to 3.3v (not VDD) through a
10k resistor (so the display is permanently on).

I guess what I'm asking is that I don't see any path to "Hi" in the
schematic. It's possible I'm still reading something wrong, though.

**Comment by karnadii** [comment]
> Hi, I was reviewing the documentation and was wondering why the connection up to VDD was omitted for the DISP pin? Was this an oversight?

I just review your question again using google translate, so I just understand what you are asking. On the first release yeah I think I miss/forget the DISP pinout, Since I am not using the DISP pinout I should connect it to VDD so the display is always high, as you point it out then I added a pull up resistor connected to DISP to address your concern. To answer your question it is my fault not seeing that.

since we want the fewer pinout usage for GPIO, we are not using the DISP pinout, so DISP is connected to VDD/3.3v (in the latest update) to make it always on. So do you have another issue regarding the newest schematic? or another question? you are just repeating what you are saying previously.

since it is 3.3v only, it is doesn't matter if it is VDD or 3.3v that connected to DISP since VDD and 3.3v is connected.

**Comment by Percentnineteen** [comment]
Sorry, not sure how or why that posted again...I suspect a GitHub issue somehow. I was asleep.

I agree with your previous fix to add the connection from DISP to VCC/3.3V
